### ISSUE TITLE
Flatpak Build

### ISSUE THREAD

**Issue by The-King-of-Toasters** [deathkiller/jazz2-native#41]
In issue #19 you mentioned wanting to build a Flatpak version, but didn't know how do do so. Well, here it is: [gh-fork-dump/tk.deat.Jazz2Resurrection](https://github.com/gh-fork-dump/tk.deat.Jazz2Resurrection). It's very easy to build using `flatpak-builder` and runs great on my Linux desktop and Steam Deck.

I'd like to submit this to [Flathub](https://flathub.org), and I need two things:

- Your permission. This is now necessary for submission to flathub. As the author you'll get full write access to the flathub git repo to make any changes (e.g. when bumping the release number).
- At least 3 screenshots of the game running. These need to be linked online so users can see them when browsing Flathub. I can take some of my own, but if you have any handy that would be great. You may not want the bandwidth costs if you upload them on `dead.tk` though.

I used flathub's [Submission documentation](https://docs.flathub.org/docs/for-app-authors/submission/) as a guide when building. You can get away with just installing `flatpak` using your distro's package manager for everything.

Some notes when doing this:

- I created an [appinfo file](https://github.com/gh-fork-dump/tk.deat.Jazz2Resurrection/blob/95710596b2e85482e314074ac6193533133bcf68/tk.deat.Jazz2Resurrection.appdata.xml) which contains program information like app type, license, bug tracker, version history, etc. It may be better to maintain that file in this repo and install it using CMake; that way it doesn't get out of sync.
- Regarding the licensing, is jazz2-native GPL 3 only or GPL 3+?

**Comment by deathkiller** [comment]
Thank you for contribution! Flatpak is requested for very long time.

> Your permission.

Sure, permission granted.

> At least 3 screenshots of the game running.

I added some screenshots to the GitHub repo and also added them to the file: https://github.com/deathkiller/jazz2-native/blob/master/Sources/project.metainfo.xml#L45-L49

> I created an appinfo file which contains program information like...

[According to this](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines#path-and-filename), AppData file should be named `.metainfo.xml` now, so I renamed it and added it to the repo (https://github.com/deathkiller/jazz2-native/blob/master/Sources/project.metainfo.xml) and CMake. If you add `-DNCINE_BUILD_FLATPAK=ON` to the yml file, it will automatically install it to `share/metainfo/tk.deat.Jazz2Resurrection.metainfo.xml` and it will also rename `.desktop` file to `tk.deat.Jazz2Resurrection.desktop` and all icons too, so `rename-desktop-file` and `rename-icon` shouldn't be necessary now. `-DNCINE_BUILD_FLATPAK=ON` will also set `-DNCINE_OVERRIDE_CONTENT_PATH` automatically, so you can remove it, and 1024px icon is excluded, so `rm -rf ${FLATPAK_DEST}/share/icons/hicolor/1024x1024` line could be also removed.

> Regarding the licensing, is jazz2-native GPL 3 only or GPL 3+?

AFAIK there is no GPL4, so I don't know what the consequences would be. But it will be probably fine as GPL3+.

Here is full `tk.deat.Jazz2Resurrection.yml` file I used for testing:
```yml
app-id: tk.deat.Jazz2Resurrection
runtime: org.freedesktop.Platform
runtime-version: "23.08"
sdk: org.freedesktop.Sdk
command: jazz2
finish-args:
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --device=all

modules:
  - name: libopenmpt
    config-opts:
      - --disable-examples
      - --disable-openmpt123
      - --disable-static
      - --disable-tests
      - --without-portaudio
      - --without-portaudiocpp
    cleanup:
      - /include
      - /lib/*.la
      - /lib/*.so
      - /lib/pkgconfig
      - /share/doc
    sources:
      - type: archive
        url: https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-0.7.3+release.autotools.tar.gz
        sha256: 2cf8369b7916b09264f3f14b9fb6cef35a6e9bee0328dec4f49d98211ccfd722
  - name: jazz2-native
    buildsystem: cmake-ninja
    config-opts:
      - -DNCINE_BUILD_FLATPAK=ON
      - -DNCINE_DOWNLOAD_DEPENDENCIES=OFF
      - -DNCINE_PREFERRED_BACKEND=SDL2
      - -DLIBOPENMPT_INCLUDE_DIR=/app/include/libopenmpt
    sources:
      - type: git
        url: https://github.com/deathkiller/jazz2-native.git
        commit: a33ee2c8afe41f964ca4e571c0d5bb5cb714af27
```

Can you check it if everything is correct, please? Then I will have to create a GIT tag (release a new version) to be able to submit it, right?
